//! Ringlane: the io_uring fast-path reactor backend (Linux). Portable
//! reactors land alongside this behind the same Reactor seam.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const buf_ring = @import("buf_ring.zig");
pub const ring = @import("ring.zig");
// gen:mods:end

test {
    // gen:tests:begin
    _ = buf_ring;
    _ = ring;
    // gen:tests:end
}
