//! LADON math substrate: logical clocks, delta-state CRDTs, and Merkle
//! anti-entropy — the building blocks of the LADON mesh state model.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const anti_entropy = @import("anti_entropy.zig");
pub const clock = @import("clock.zig");
pub const convergence = @import("convergence.zig");
pub const crdt = @import("crdt.zig");
pub const merkle = @import("merkle.zig");
pub const state = @import("state.zig");
// gen:mods:end

test {
    // gen:tests:begin
    _ = anti_entropy;
    _ = clock;
    _ = convergence;
    _ = crdt;
    _ = merkle;
    _ = state;
    // gen:tests:end
}
