//! SUIMYAKU math substrate: logical clocks, delta-state CRDTs, and Merkle
//! anti-entropy — the building blocks of the SUIMYAKU mesh state model.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const anti_entropy = @import("anti_entropy.zig");
pub const clock = @import("clock.zig");
pub const convergence = @import("convergence.zig");
pub const delta_codec = @import("delta_codec.zig");
pub const goryu = @import("goryu.zig");
pub const goryu_props = @import("goryu_props.zig");
pub const media = @import("media.zig");
pub const membership_view = @import("membership_view.zig");
pub const merkle = @import("merkle.zig");
pub const merkle_props = @import("merkle_props.zig");
pub const state_props = @import("state_props.zig");
pub const state = @import("state.zig");
// gen:mods:end

test {
    // gen:tests:begin
    _ = anti_entropy;
    _ = clock;
    _ = convergence;
    _ = delta_codec;
    _ = goryu;
    _ = goryu_props;
    _ = media;
    _ = membership_view;
    _ = merkle;
    _ = merkle_props;
    _ = state_props;
    _ = state;
    // gen:tests:end
}
