//! mizuchi-substrate — reactor (Ringlane), allocators, lock-free queues,
//! data structures, SUIMYAKU math (CRDT/HLC/vclock/Merkle), and the deterministic
//! simulation runtime (Deterministic Ocean). Skeleton; see planning/01.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const io = @import("io/root.zig");
pub const queue = @import("queue.zig");
pub const reactor = @import("reactor.zig");
pub const sazanami = @import("sazanami.zig");
pub const sim = @import("sim.zig");
pub const sketch = @import("sketch.zig");
pub const suimyaku = @import("suimyaku/root.zig");
// gen:mods:end

pub const Reactor = reactor.Reactor;
pub const SystemReactor = reactor.SystemReactor;
pub const SimReactor = reactor.SimReactor;

test {
    // gen:tests:begin
    _ = io;
    _ = queue;
    _ = reactor;
    _ = sazanami;
    _ = sim;
    _ = sketch;
    _ = suimyaku;
    // gen:tests:end
}
