//! mizuchi-substrate — reactor (Ringlane), allocators, lock-free queues,
//! data structures, SUIMYAKU math (CRDT/HLC/vclock/Merkle), and the deterministic
//! simulation runtime (Deterministic Ocean). Skeleton; see planning/01.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const admission = @import("admission.zig");
pub const arena = @import("arena.zig");
pub const geoip = @import("geoip.zig");
pub const io = @import("io/root.zig");
pub const ip_cidr = @import("ip_cidr.zig");
pub const lotus = @import("lotus.zig");
pub const opcodec_frame = @import("opcodec_frame.zig");
pub const platform = @import("platform.zig");
pub const queue = @import("queue.zig");
pub const raptorq = @import("raptorq.zig");
pub const rateless = @import("rateless.zig");
pub const reactor = @import("reactor.zig");
pub const ryusen = @import("ryusen.zig");
pub const sazanami_props = @import("sazanami_props.zig");
pub const sazanami = @import("sazanami.zig");
pub const sim_net = @import("sim_net.zig");
pub const sim = @import("sim.zig");
pub const sketch = @import("sketch.zig");
pub const suimyaku = @import("suimyaku/root.zig");
pub const timer = @import("timer.zig");
pub const timer_wheel = @import("timer_wheel.zig");
pub const trace = @import("trace.zig");
pub const upgrade_capsule = @import("upgrade_capsule.zig");
pub const utf8 = @import("utf8.zig");
// gen:mods:end

pub const Reactor = reactor.Reactor;
pub const SystemReactor = reactor.SystemReactor;
pub const SimReactor = reactor.SimReactor;

test {
    // gen:tests:begin
    _ = admission;
    _ = arena;
    _ = geoip;
    _ = io;
    _ = ip_cidr;
    _ = lotus;
    _ = opcodec_frame;
    _ = platform;
    _ = queue;
    _ = raptorq;
    _ = rateless;
    _ = reactor;
    _ = ryusen;
    _ = sazanami_props;
    _ = sazanami;
    _ = sim_net;
    _ = sim;
    _ = sketch;
    _ = suimyaku;
    _ = timer;
    _ = timer_wheel;
    _ = trace;
    _ = upgrade_capsule;
    _ = utf8;
    // gen:tests:end
}
