//! mizuchi-substrate — reactor (Ringlane), allocators, lock-free queues,
//! data structures, SUIMYAKU math (CRDT/HLC/vclock/Merkle), and the deterministic
//! simulation runtime (Deterministic Ocean). Skeleton; see planning/01.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const admission = @import("admission.zig");
pub const arena = @import("arena.zig");
pub const bbr = @import("bbr.zig");
pub const flow = @import("flow.zig");
pub const geoip = @import("geoip.zig");
pub const gf256 = @import("gf256.zig");
pub const io = @import("io/root.zig");
pub const ip_cidr = @import("ip_cidr.zig");
pub const l4s = @import("l4s.zig");
pub const loss_recovery = @import("loss_recovery.zig");
pub const lotus = @import("lotus.zig");
pub const metrics = @import("metrics.zig");
pub const opcodec_frame = @import("opcodec_frame.zig");
pub const pacing = @import("pacing.zig");
pub const platform = @import("platform.zig");
pub const qlog = @import("qlog.zig");
pub const queue = @import("queue.zig");
pub const raptorq = @import("raptorq.zig");
pub const rateless = @import("rateless.zig");
pub const reactor = @import("reactor.zig");
pub const ryusen = @import("ryusen.zig");
pub const sazanami_props = @import("sazanami_props.zig");
pub const sazanami = @import("sazanami.zig");
pub const scheduler = @import("scheduler.zig");
pub const sim_net = @import("sim_net.zig");
pub const sim = @import("sim.zig");
pub const sketch = @import("sketch.zig");
pub const suimyaku = @import("suimyaku/root.zig");
pub const timer = @import("timer.zig");
pub const timer_wheel = @import("timer_wheel.zig");
pub const trace = @import("trace.zig");
pub const turn = @import("turn.zig");
pub const upgrade_capsule = @import("upgrade_capsule.zig");
pub const utf8 = @import("utf8.zig");
pub const wal = @import("wal.zig");
// gen:mods:end

pub const Reactor = reactor.Reactor;
pub const SystemReactor = reactor.SystemReactor;
pub const SimReactor = reactor.SimReactor;

test {
    // gen:tests:begin
    _ = admission;
    _ = arena;
    _ = bbr;
    _ = flow;
    _ = geoip;
    _ = gf256;
    _ = io;
    _ = ip_cidr;
    _ = l4s;
    _ = loss_recovery;
    _ = lotus;
    _ = metrics;
    _ = opcodec_frame;
    _ = pacing;
    _ = platform;
    _ = qlog;
    _ = queue;
    _ = raptorq;
    _ = rateless;
    _ = reactor;
    _ = ryusen;
    _ = sazanami_props;
    _ = sazanami;
    _ = scheduler;
    _ = sim_net;
    _ = sim;
    _ = sketch;
    _ = suimyaku;
    _ = timer;
    _ = timer_wheel;
    _ = trace;
    _ = turn;
    _ = upgrade_capsule;
    _ = utf8;
    _ = wal;
    // gen:tests:end
}
