//! SerpentRegistry comptime daemon module registry.
//!
//! Mizuchi statically assembles daemon modules instead of runtime-loading
//! runtime MAPI objects. This file keeps the registry self-contained for early
//! daemon work: module metadata is validated at comptime, command and hook
//! tables are generated once, and dispatch is a small table scan over immutable
//! declarations.
const std = @import("std");

/// Command handler used by registry dispatch.
pub const CommandHandler = *const fn (ctx: *anyopaque, invocation: CommandInvocation) anyerror!void;

/// Hook handler used by registry hook dispatch.
pub const HookHandler = *const fn (ctx: *anyopaque, payload: *anyopaque) anyerror!HookResult;

/// A parsed command invocation passed to command handlers.
pub const CommandInvocation = struct {
    name: []const u8,
    params: []const []const u8,
};

/// Outcome of command lookup and minimum-parameter validation.
pub const DispatchResult = union(enum) {
    handled,
    not_found,
    too_few_params: usize,
};

/// Hook execution result. A stopping hook prevents later bindings from firing.
pub const HookResult = enum {
    continue_,
    stop,
};

/// Hook priority. Lower values run first; equal priorities keep module order.
pub const HookPriority = enum(u8) {
    first = 0,
    early = 1,
    normal = 2,
    late = 3,
    last = 4,
};

/// Capability class.
pub const CapKind = enum {
    client,
    server,
};

/// Mode namespace.
pub const ModeClass = enum {
    channel,
    user,
};

/// Command declaration exported by a module.
pub const CommandSpec = struct {
    name: []const u8,
    min_params: usize = 0,
    handler: CommandHandler,
};

/// Hook binding exported by a module.
pub const HookBinding = struct {
    hook: []const u8,
    priority: HookPriority = .normal,
    handler: HookHandler,
};

/// Capability declaration exported by a module.
pub const CapSpec = struct {
    name: []const u8,
    kind: CapKind = .client,
};

/// Channel mode declaration exported by a module.
pub const ChanModeSpec = struct {
    letter: u8,
    name: []const u8 = "",
};

/// User mode declaration exported by a module.
pub const UserModeSpec = struct {
    letter: u8,
    name: []const u8 = "",
};

/// Numeric declaration exported by a module.
pub const NumericSpec = struct {
    code: u16,
    name: []const u8,
};

/// ISUPPORT token declaration exported by a module.
pub const ISupportSpec = struct {
    token: []const u8,
    value: ?[]const u8 = null,
};

/// Complete comptime module declaration.
pub const Module = struct {
    id: []const u8,
    requires: []const []const u8 = &.{},
    conflicts: []const []const u8 = &.{},

    commands: []const CommandSpec = &.{},
    hooks: []const HookBinding = &.{},
    caps: []const CapSpec = &.{},
    chanmodes: []const ChanModeSpec = &.{},
    usermodes: []const UserModeSpec = &.{},
    numerics: []const NumericSpec = &.{},
    isupport: []const ISupportSpec = &.{},
};

/// Validation failure kind used by tests and by Registry compile errors.
pub const ValidationKind = enum {
    duplicate_module,
    missing_dependency,
    module_conflict,
    duplicate_command,
    duplicate_cap,
    duplicate_channel_mode,
    duplicate_user_mode,
    duplicate_numeric,
};

/// First registry validation failure found.
pub const ValidationError = struct {
    kind: ValidationKind,
    module_id: []const u8,
    other_module_id: []const u8 = "",
    name: []const u8 = "",
    code: u16 = 0,
    mode: u8 = 0,
};

/// Immutable command table row generated by Registry.
pub const CommandEntry = struct {
    module_id: []const u8,
    spec: CommandSpec,
};

/// Immutable hook table row generated by Registry.
pub const HookEntry = struct {
    module_id: []const u8,
    binding: HookBinding,
};

/// Validate a module set without making the caller fail to compile.
pub fn validate(comptime mods: []const Module) ?ValidationError {
    for (mods, 0..) |module, module_index| {
        for (mods[0..module_index]) |other| {
            if (std.mem.eql(u8, module.id, other.id)) {
                return .{
                    .kind = .duplicate_module,
                    .module_id = module.id,
                    .other_module_id = other.id,
                    .name = module.id,
                };
            }
        }

        for (module.requires) |required| {
            if (!hasModule(mods, required)) {
                return .{
                    .kind = .missing_dependency,
                    .module_id = module.id,
                    .name = required,
                };
            }
        }

        for (module.conflicts) |conflict| {
            if (hasModule(mods, conflict)) {
                return .{
                    .kind = .module_conflict,
                    .module_id = module.id,
                    .other_module_id = conflict,
                    .name = conflict,
                };
            }
        }
    }

    for (mods, 0..) |module, module_index| {
        for (module.commands, 0..) |command, command_index| {
            if (findPriorCommand(mods, module_index, command_index, command.name)) |other| {
                return .{
                    .kind = .duplicate_command,
                    .module_id = module.id,
                    .other_module_id = other,
                    .name = command.name,
                };
            }
        }

        for (module.caps, 0..) |cap, cap_index| {
            if (findPriorCap(mods, module_index, cap_index, cap.name)) |other| {
                return .{
                    .kind = .duplicate_cap,
                    .module_id = module.id,
                    .other_module_id = other,
                    .name = cap.name,
                };
            }
        }

        for (module.chanmodes, 0..) |mode, mode_index| {
            if (findPriorChanMode(mods, module_index, mode_index, mode.letter)) |other| {
                return .{
                    .kind = .duplicate_channel_mode,
                    .module_id = module.id,
                    .other_module_id = other,
                    .mode = mode.letter,
                };
            }
        }

        for (module.usermodes, 0..) |mode, mode_index| {
            if (findPriorUserMode(mods, module_index, mode_index, mode.letter)) |other| {
                return .{
                    .kind = .duplicate_user_mode,
                    .module_id = module.id,
                    .other_module_id = other,
                    .mode = mode.letter,
                };
            }
        }

        for (module.numerics, 0..) |numeric, numeric_index| {
            if (findPriorNumeric(mods, module_index, numeric_index, numeric.code)) |other| {
                return .{
                    .kind = .duplicate_numeric,
                    .module_id = module.id,
                    .other_module_id = other,
                    .code = numeric.code,
                };
            }
        }
    }

    return null;
}

/// Build the immutable registry type for a comptime module set.
pub fn Registry(comptime mods: []const Module) type {
    comptime {
        if (validate(mods)) |err| {
            @compileError(validationMessage(err));
        }
    }

    const command_table = comptime buildCommandTable(mods);
    const hook_table = comptime buildHookTable(mods);
    const cap_table = comptime buildCapTable(mods);
    const chanmode_table = comptime buildChanModeTable(mods);
    const usermode_table = comptime buildUserModeTable(mods);
    const numeric_table = comptime buildNumericTable(mods);
    const isupport_table = comptime buildISupportTable(mods);

    return struct {
        pub const modules = mods;
        pub const commands = command_table;
        pub const hooks = hook_table;
        pub const caps = cap_table;
        pub const chanmodes = chanmode_table;
        pub const usermodes = usermode_table;
        pub const numerics = numeric_table;
        pub const isupport = isupport_table;

        pub fn lookupCommand(name: []const u8) ?CommandEntry {
            for (commands) |entry| {
                if (std.ascii.eqlIgnoreCase(entry.spec.name, name)) {
                    return entry;
                }
            }
            return null;
        }

        pub fn dispatch(
            ctx: *anyopaque,
            command_name: []const u8,
            params: []const []const u8,
        ) anyerror!DispatchResult {
            const entry = lookupCommand(command_name) orelse return .not_found;
            if (params.len < entry.spec.min_params) {
                return .{ .too_few_params = entry.spec.min_params };
            }

            try entry.spec.handler(ctx, .{
                .name = entry.spec.name,
                .params = params,
            });
            return .handled;
        }

        pub fn callHook(
            comptime hook: []const u8,
            ctx: *anyopaque,
            payload: *anyopaque,
        ) anyerror!HookResult {
            inline for (hooks) |entry| {
                if (std.mem.eql(u8, entry.binding.hook, hook)) {
                    const result = try entry.binding.handler(ctx, payload);
                    if (result == .stop) return .stop;
                }
            }
            return .continue_;
        }
    };
}

fn validationMessage(comptime err: ValidationError) []const u8 {
    return switch (err.kind) {
        .duplicate_module => "SerpentRegistry: duplicate module id",
        .missing_dependency => "SerpentRegistry: missing required module",
        .module_conflict => "SerpentRegistry: conflicting modules selected",
        .duplicate_command => "SerpentRegistry: duplicate command name",
        .duplicate_cap => "SerpentRegistry: duplicate capability name",
        .duplicate_channel_mode => "SerpentRegistry: duplicate channel mode letter",
        .duplicate_user_mode => "SerpentRegistry: duplicate user mode letter",
        .duplicate_numeric => "SerpentRegistry: duplicate numeric",
    };
}

fn hasModule(comptime mods: []const Module, id: []const u8) bool {
    for (mods) |module| {
        if (std.mem.eql(u8, module.id, id)) return true;
    }
    return false;
}

fn findPriorCommand(
    comptime mods: []const Module,
    module_index: usize,
    command_index: usize,
    name: []const u8,
) ?[]const u8 {
    for (mods, 0..) |module, current_module_index| {
        if (current_module_index > module_index) break;
        const limit = if (current_module_index == module_index) command_index else module.commands.len;
        for (module.commands[0..limit]) |command| {
            if (std.ascii.eqlIgnoreCase(command.name, name)) return module.id;
        }
    }
    return null;
}

fn findPriorCap(
    comptime mods: []const Module,
    module_index: usize,
    cap_index: usize,
    name: []const u8,
) ?[]const u8 {
    for (mods, 0..) |module, current_module_index| {
        if (current_module_index > module_index) break;
        const limit = if (current_module_index == module_index) cap_index else module.caps.len;
        for (module.caps[0..limit]) |cap| {
            if (std.mem.eql(u8, cap.name, name)) return module.id;
        }
    }
    return null;
}

fn findPriorChanMode(
    comptime mods: []const Module,
    module_index: usize,
    mode_index: usize,
    letter: u8,
) ?[]const u8 {
    for (mods, 0..) |module, current_module_index| {
        if (current_module_index > module_index) break;
        const limit = if (current_module_index == module_index) mode_index else module.chanmodes.len;
        for (module.chanmodes[0..limit]) |mode| {
            if (mode.letter == letter) return module.id;
        }
    }
    return null;
}

fn findPriorUserMode(
    comptime mods: []const Module,
    module_index: usize,
    mode_index: usize,
    letter: u8,
) ?[]const u8 {
    for (mods, 0..) |module, current_module_index| {
        if (current_module_index > module_index) break;
        const limit = if (current_module_index == module_index) mode_index else module.usermodes.len;
        for (module.usermodes[0..limit]) |mode| {
            if (mode.letter == letter) return module.id;
        }
    }
    return null;
}

fn findPriorNumeric(
    comptime mods: []const Module,
    module_index: usize,
    numeric_index: usize,
    code: u16,
) ?[]const u8 {
    for (mods, 0..) |module, current_module_index| {
        if (current_module_index > module_index) break;
        const limit = if (current_module_index == module_index) numeric_index else module.numerics.len;
        for (module.numerics[0..limit]) |numeric| {
            if (numeric.code == code) return module.id;
        }
    }
    return null;
}

fn countCommands(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.commands.len;
    return total;
}

fn countHooks(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.hooks.len;
    return total;
}

fn countCaps(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.caps.len;
    return total;
}

fn countChanModes(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.chanmodes.len;
    return total;
}

fn countUserModes(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.usermodes.len;
    return total;
}

fn countNumerics(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.numerics.len;
    return total;
}

fn countISupport(comptime mods: []const Module) comptime_int {
    var total = 0;
    for (mods) |module| total += module.isupport.len;
    return total;
}

fn buildCommandTable(comptime mods: []const Module) [countCommands(mods)]CommandEntry {
    var table: [countCommands(mods)]CommandEntry = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.commands) |command| {
            table[index] = .{ .module_id = module.id, .spec = command };
            index += 1;
        }
    }
    return table;
}

fn buildHookTable(comptime mods: []const Module) [countHooks(mods)]HookEntry {
    var table: [countHooks(mods)]HookEntry = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.hooks) |binding| {
            table[index] = .{ .module_id = module.id, .binding = binding };
            index += 1;
        }
    }

    var sorted = 1;
    while (sorted < table.len) : (sorted += 1) {
        const item = table[sorted];
        var scan = sorted;
        while (scan > 0 and hookPrecedes(item, table[scan - 1])) : (scan -= 1) {
            table[scan] = table[scan - 1];
        }
        table[scan] = item;
    }

    return table;
}

fn buildCapTable(comptime mods: []const Module) [countCaps(mods)]CapSpec {
    var table: [countCaps(mods)]CapSpec = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.caps) |cap| {
            table[index] = cap;
            index += 1;
        }
    }
    return table;
}

fn buildChanModeTable(comptime mods: []const Module) [countChanModes(mods)]ChanModeSpec {
    var table: [countChanModes(mods)]ChanModeSpec = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.chanmodes) |mode| {
            table[index] = mode;
            index += 1;
        }
    }
    return table;
}

fn buildUserModeTable(comptime mods: []const Module) [countUserModes(mods)]UserModeSpec {
    var table: [countUserModes(mods)]UserModeSpec = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.usermodes) |mode| {
            table[index] = mode;
            index += 1;
        }
    }
    return table;
}

fn buildNumericTable(comptime mods: []const Module) [countNumerics(mods)]NumericSpec {
    var table: [countNumerics(mods)]NumericSpec = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.numerics) |numeric| {
            table[index] = numeric;
            index += 1;
        }
    }
    return table;
}

fn buildISupportTable(comptime mods: []const Module) [countISupport(mods)]ISupportSpec {
    var table: [countISupport(mods)]ISupportSpec = undefined;
    var index = 0;
    for (mods) |module| {
        for (module.isupport) |token| {
            table[index] = token;
            index += 1;
        }
    }
    return table;
}

fn hookPrecedes(left: HookEntry, right: HookEntry) bool {
    return @intFromEnum(left.binding.priority) < @intFromEnum(right.binding.priority);
}

const TestCtx = struct {
    command_count: usize = 0,
    order: [8]u8 = undefined,
    order_len: usize = 0,

    fn record(self: *TestCtx, value: u8) void {
        self.order[self.order_len] = value;
        self.order_len += 1;
    }
};

fn pingHandler(ctx: *anyopaque, invocation: CommandInvocation) anyerror!void {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    try std.testing.expectEqual(@as(usize, 1), invocation.params.len);
    self.command_count += 1;
}

fn pongHandler(ctx: *anyopaque, _: CommandInvocation) anyerror!void {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    self.command_count += 10;
}

fn hookOne(ctx: *anyopaque, _: *anyopaque) anyerror!HookResult {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    self.record(1);
    return .continue_;
}

fn hookTwo(ctx: *anyopaque, _: *anyopaque) anyerror!HookResult {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    self.record(2);
    return .continue_;
}

fn hookThree(ctx: *anyopaque, _: *anyopaque) anyerror!HookResult {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    self.record(3);
    return .continue_;
}

fn hookFour(ctx: *anyopaque, _: *anyopaque) anyerror!HookResult {
    const self: *TestCtx = @ptrCast(@alignCast(ctx));
    self.record(4);
    return .continue_;
}

const coreModule = Module{
    .id = "core",
    .commands = &.{
        .{ .name = "PING", .min_params = 1, .handler = pingHandler },
    },
    .hooks = &.{
        .{ .hook = "client.register", .priority = .normal, .handler = hookOne },
    },
    .caps = &.{
        .{ .name = "server-time" },
    },
    .chanmodes = &.{
        .{ .letter = 'n', .name = "no-external" },
    },
    .usermodes = &.{
        .{ .letter = 'i', .name = "invisible" },
    },
    .numerics = &.{
        .{ .code = 1, .name = "RPL_WELCOME" },
    },
    .isupport = &.{
        .{ .token = "CHANTYPES", .value = "#" },
    },
};

const capModule = Module{
    .id = "cap",
    .requires = &.{"core"},
    .commands = &.{
        .{ .name = "PONG", .handler = pongHandler },
    },
    .hooks = &.{
        .{ .hook = "client.register", .priority = .first, .handler = hookTwo },
        .{ .hook = "client.register", .priority = .normal, .handler = hookThree },
    },
    .caps = &.{
        .{ .name = "message-tags" },
    },
};

const lateModule = Module{
    .id = "late",
    .hooks = &.{
        .{ .hook = "client.register", .priority = .late, .handler = hookFour },
    },
};

const duplicateCommandModule = Module{
    .id = "dupe",
    .commands = &.{
        .{ .name = "ping", .handler = pongHandler },
    },
};

test "registry dispatches known commands and reports unknown commands" {
    const R = Registry(&.{ coreModule, capModule, lateModule });
    var ctx = TestCtx{};
    const params = [_][]const u8{"token"};

    const handled = try R.dispatch(&ctx, "PING", &params);
    try std.testing.expectEqual(DispatchResult.handled, handled);
    try std.testing.expectEqual(@as(usize, 1), ctx.command_count);

    const lower = try R.dispatch(&ctx, "pong", &.{});
    try std.testing.expectEqual(DispatchResult.handled, lower);
    try std.testing.expectEqual(@as(usize, 11), ctx.command_count);

    const missing = try R.dispatch(&ctx, "NOPE", &.{});
    try std.testing.expectEqual(DispatchResult.not_found, missing);
}

test "registry checks command minimum parameters before calling handlers" {
    const R = Registry(&.{coreModule});
    var ctx = TestCtx{};

    const result = try R.dispatch(&ctx, "PING", &.{});
    try std.testing.expectEqual(DispatchResult{ .too_few_params = 1 }, result);
    try std.testing.expectEqual(@as(usize, 0), ctx.command_count);
}

test "hooks fire in priority order with stable module-order ties" {
    const R = Registry(&.{ coreModule, capModule, lateModule });
    var ctx = TestCtx{};
    var payload: u8 = 0;

    const result = try R.callHook("client.register", &ctx, &payload);
    try std.testing.expectEqual(HookResult.continue_, result);
    try std.testing.expectEqualSlices(u8, &.{ 2, 1, 3, 4 }, ctx.order[0..ctx.order_len]);
}

test "validator recognizes duplicate command names without failing this file" {
    const err = validate(&.{ coreModule, duplicateCommandModule }) orelse
        return error.ExpectedDuplicateCommand;

    try std.testing.expectEqual(ValidationKind.duplicate_command, err.kind);
    try std.testing.expect(std.ascii.eqlIgnoreCase("PING", err.name));
    try std.testing.expectEqualStrings("dupe", err.module_id);
    try std.testing.expectEqualStrings("core", err.other_module_id);
}
