//! mizuchi-daemon — core, SerpentRegistry (comptime modules), CapProof
//! permission lattice, services, MizuStore, media. Skeleton; see planning/03.
const std = @import("std");
const substrate = @import("../substrate/root.zig");

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const activity_subscriptions = @import("activity_subscriptions.zig");
pub const ban_db = @import("ban_db.zig");
pub const chanmode = @import("chanmode.zig");
pub const client = @import("client.zig");
pub const clone_detect = @import("clone_detect.zig");
pub const commands = @import("commands.zig");
pub const config_boot = @import("config_boot.zig");
pub const config = @import("config.zig");
pub const config_format = @import("config_format.zig");
pub const config_schema = @import("config_schema.zig");
pub const dispatch = @import("dispatch.zig");
pub const event_spine = @import("event_spine.zig");
pub const flood = @import("flood.zig");
pub const flood_guard = @import("flood_guard.zig");
pub const oper = @import("oper.zig");
pub const registry = @import("registry.zig");
pub const s2s_dst = @import("s2s_dst.zig");
pub const s2s_link = @import("s2s_link.zig");
pub const sasl_bridge = @import("sasl_bridge.zig");
pub const secure_s2s_link = @import("secure_s2s_link.zig");
pub const server = @import("server.zig");
pub const server_stats = @import("server_stats.zig");
pub const services = @import("services.zig");
pub const store = @import("store.zig");
pub const whois = @import("whois.zig");
pub const whowas = @import("whowas.zig");
pub const world_projection = @import("world_projection.zig");
pub const world = @import("world.zig");
// gen:mods:end

test {
    // gen:tests:begin
    _ = activity_subscriptions;
    _ = ban_db;
    _ = chanmode;
    _ = client;
    _ = clone_detect;
    _ = commands;
    _ = config_boot;
    _ = config;
    _ = config_format;
    _ = config_schema;
    _ = dispatch;
    _ = event_spine;
    _ = flood;
    _ = flood_guard;
    _ = oper;
    _ = registry;
    _ = s2s_dst;
    _ = s2s_link;
    _ = sasl_bridge;
    _ = secure_s2s_link;
    _ = server;
    _ = server_stats;
    _ = services;
    _ = store;
    _ = whois;
    _ = whowas;
    _ = world_projection;
    _ = world;
    // gen:tests:end
}

pub const Daemon = struct {
    reactor: substrate.Reactor,

    pub fn init(reactor: substrate.Reactor) Daemon {
        return .{ .reactor = reactor };
    }

    /// M0 placeholder. M0 exit criterion: accept a TCP client and answer PING.
    /// The Ringlane listener + IRC line parser land in M1/M2; today this proves
    /// the boot path and the DST clock seam are wired end-to-end.
    pub fn boot(self: *Daemon) void {
        std.debug.print(
            "mizuchi: boot ok (monotonic clock = {d} ms) — TCP listener: TODO (M1)\n",
            .{self.reactor.nowMillis()},
        );
    }
};

test "daemon boots against the deterministic reactor" {
    var sim = substrate.SimReactor.init(42);
    var d = Daemon.init(sim.reactor());
    try std.testing.expectEqual(@as(i64, 42), d.reactor.nowMillis());
}
