//! mizuchi-proto — IRC/IRCv3/IRCX/SUIMYAKU/TSUMUGI schemas, the comptime codec
//! generator (Codec Loom) and the canonical wire format (CoilPack).
//! Skeleton; see planning/04.

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const away = @import("away.zig");
pub const batch = @import("batch.zig");
pub const cap = @import("cap.zig");
pub const chathistory = @import("chathistory.zig");
pub const chghost = @import("chghost.zig");
pub const cloak = @import("cloak.zig");
pub const coilpack = @import("coilpack.zig");
pub const ctcp = @import("ctcp.zig");
pub const dns = @import("dns.zig");
pub const extban = @import("extban.zig");
pub const frame = @import("frame.zig");
pub const irc_line = @import("irc_line.zig");
pub const ircx = @import("ircx.zig");
pub const isupport = @import("isupport.zig");
pub const list = @import("list.zig");
pub const meshpass = @import("meshpass.zig");
pub const metadata = @import("metadata.zig");
pub const monitor = @import("monitor.zig");
pub const msgedit = @import("msgedit.zig");
pub const msgtags = @import("msgtags.zig");
pub const multiline = @import("multiline.zig");
pub const numeric = @import("numeric.zig");
pub const read_marker = @import("read_marker.zig");
pub const sasl = @import("sasl.zig");
pub const standard_replies = @import("standard_replies.zig");
pub const sts = @import("sts.zig");
pub const suimyaku_peer = @import("suimyaku_peer.zig");
pub const tsumugi = @import("tsumugi.zig");
pub const usermode = @import("usermode.zig");
pub const websocket = @import("websocket.zig");
pub const who = @import("who.zig");
// gen:mods:end

/// Native server-to-server mesh protocol (replaces TS6 entirely).
pub const s2s_protocol = "SUIMYAKU";

/// Transport security wrapper for post-auth mesh frames.
pub const transport_security = "TSUMUGI";

test {
    // gen:tests:begin
    _ = away;
    _ = batch;
    _ = cap;
    _ = chathistory;
    _ = chghost;
    _ = cloak;
    _ = coilpack;
    _ = ctcp;
    _ = dns;
    _ = extban;
    _ = frame;
    _ = irc_line;
    _ = ircx;
    _ = isupport;
    _ = list;
    _ = meshpass;
    _ = metadata;
    _ = monitor;
    _ = msgedit;
    _ = msgtags;
    _ = multiline;
    _ = numeric;
    _ = read_marker;
    _ = sasl;
    _ = standard_replies;
    _ = sts;
    _ = suimyaku_peer;
    _ = tsumugi;
    _ = usermode;
    _ = websocket;
    _ = who;
    // gen:tests:end
}
