//! mizuchi-proto — IRC/IRCv3/IRCX/SUIMYAKU/TSUMUGI schemas, the comptime codec
//! generator (Codec Loom) and the canonical wire format (CoilPack).
//! Skeleton; see planning/04.

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const account_notify = @import("account_notify.zig");
pub const away = @import("away.zig");
pub const batch = @import("batch.zig");
pub const bot_mode = @import("bot_mode.zig");
pub const cap = @import("cap.zig");
pub const channel_rename = @import("channel_rename.zig");
pub const chathistory = @import("chathistory.zig");
pub const chghost = @import("chghost.zig");
pub const cloak = @import("cloak.zig");
pub const coilpack = @import("coilpack.zig");
pub const coilpack_props = @import("coilpack_props.zig");
pub const ctcp = @import("ctcp.zig");
pub const dns = @import("dns.zig");
pub const dns_props = @import("dns_props.zig");
pub const echo_message = @import("echo_message.zig");
pub const extban = @import("extban.zig");
pub const extban_props = @import("extban_props.zig");
pub const extended_join = @import("extended_join.zig");
pub const extended_monitor = @import("extended_monitor.zig");
pub const frame = @import("frame.zig");
pub const frame_props = @import("frame_props.zig");
pub const invite_notify = @import("invite_notify.zig");
pub const irc_line = @import("irc_line.zig");
pub const irc_line_props = @import("irc_line_props.zig");
pub const ircx = @import("ircx.zig");
pub const ircx_props = @import("ircx_props.zig");
pub const isupport = @import("isupport.zig");
pub const knock = @import("knock.zig");
pub const list = @import("list.zig");
pub const meshpass = @import("meshpass.zig");
pub const metadata = @import("metadata.zig");
pub const monitor = @import("monitor.zig");
pub const msgedit = @import("msgedit.zig");
pub const msgtags = @import("msgtags.zig");
pub const multiline = @import("multiline.zig");
pub const names_reply = @import("names_reply.zig");
pub const numeric = @import("numeric.zig");
pub const read_marker = @import("read_marker.zig");
pub const sasl_props = @import("sasl_props.zig");
pub const sasl = @import("sasl.zig");
pub const standard_replies = @import("standard_replies.zig");
pub const sts = @import("sts.zig");
pub const suimyaku_peer = @import("suimyaku_peer.zig");
pub const tsumugi = @import("tsumugi.zig");
pub const usermode = @import("usermode.zig");
pub const utf8_only = @import("utf8_only.zig");
pub const websocket_props = @import("websocket_props.zig");
pub const websocket = @import("websocket.zig");
pub const who = @import("who.zig");
// gen:mods:end

/// Native server-to-server mesh protocol (replaces TS6 entirely).
pub const s2s_protocol = "SUIMYAKU";

/// Transport security wrapper for post-auth mesh frames.
pub const transport_security = "TSUMUGI";

test {
    // gen:tests:begin
    _ = account_notify;
    _ = away;
    _ = batch;
    _ = bot_mode;
    _ = cap;
    _ = channel_rename;
    _ = chathistory;
    _ = chghost;
    _ = cloak;
    _ = coilpack;
    _ = coilpack_props;
    _ = ctcp;
    _ = dns;
    _ = dns_props;
    _ = echo_message;
    _ = extban;
    _ = extban_props;
    _ = extended_join;
    _ = extended_monitor;
    _ = frame;
    _ = frame_props;
    _ = invite_notify;
    _ = irc_line;
    _ = irc_line_props;
    _ = ircx;
    _ = ircx_props;
    _ = isupport;
    _ = knock;
    _ = list;
    _ = meshpass;
    _ = metadata;
    _ = monitor;
    _ = msgedit;
    _ = msgtags;
    _ = multiline;
    _ = names_reply;
    _ = numeric;
    _ = read_marker;
    _ = sasl_props;
    _ = sasl;
    _ = standard_replies;
    _ = sts;
    _ = suimyaku_peer;
    _ = tsumugi;
    _ = usermode;
    _ = utf8_only;
    _ = websocket_props;
    _ = websocket;
    _ = who;
    // gen:tests:end
}
