//! mizuchi-proto — IRC/IRCv3/IRCX/SUIMYAKU/TSUMUGI schemas, the comptime codec
//! generator (Codec Loom) and the canonical wire format (CoilPack).
//! Skeleton; see planning/04.

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const away = @import("away.zig");
pub const batch = @import("batch.zig");
pub const cap = @import("cap.zig");
pub const cloak = @import("cloak.zig");
pub const coilpack = @import("coilpack.zig");
pub const ctcp = @import("ctcp.zig");
pub const extban = @import("extban.zig");
pub const frame = @import("frame.zig");
pub const irc_line = @import("irc_line.zig");
pub const ircx = @import("ircx.zig");
pub const meshpass = @import("meshpass.zig");
pub const monitor = @import("monitor.zig");
pub const msgtags = @import("msgtags.zig");
pub const numeric = @import("numeric.zig");
pub const sasl = @import("sasl.zig");
pub const sts = @import("sts.zig");
pub const tsumugi = @import("tsumugi.zig");
pub const websocket = @import("websocket.zig");
// gen:mods:end

/// Native server-to-server mesh protocol (replaces TS6 entirely).
pub const s2s_protocol = "SUIMYAKU";

/// Transport security wrapper for post-auth mesh frames.
pub const transport_security = "TSUMUGI";

test {
    // gen:tests:begin
    _ = away;
    _ = batch;
    _ = cap;
    _ = cloak;
    _ = coilpack;
    _ = ctcp;
    _ = extban;
    _ = frame;
    _ = irc_line;
    _ = ircx;
    _ = meshpass;
    _ = monitor;
    _ = msgtags;
    _ = numeric;
    _ = sasl;
    _ = sts;
    _ = tsumugi;
    _ = websocket;
    // gen:tests:end
}
