//! mizuchi-crypto — primitives, TLS 1.3-only, TSUMUGI v2 (PQ-hybrid), and the
//! Secret(T) constant-time discipline. Skeleton; see planning/02.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const aead = @import("aead.zig");
pub const hash = @import("hash.zig");
pub const kx = @import("kx.zig");
pub const random = @import("random.zig");
pub const secret = @import("secret.zig");
pub const sign = @import("sign.zig");
pub const tls = @import("tls.zig");
pub const x509 = @import("x509.zig");
// gen:mods:end

pub const Secret = secret.Secret;

test {
    // gen:tests:begin
    _ = aead;
    _ = hash;
    _ = kx;
    _ = random;
    _ = secret;
    _ = sign;
    _ = tls;
    _ = x509;
    // gen:tests:end
}
