//! orochi-crypto — primitives, TLS 1.3-only, TSUMUGI v2 (PQ-hybrid), and the
//! Secret(T) constant-time discipline. Skeleton; see planning/02.
// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const aead = @import("aead.zig");
pub const aead_kat = @import("aead_kat.zig");
pub const aead_stream = @import("aead_stream.zig");
pub const age = @import("age.zig");
pub const argon2_kdf = @import("argon2_kdf.zig");
pub const cose = @import("cose.zig");
pub const crl = @import("crl.zig");
pub const ecdh_p256 = @import("ecdh_p256.zig");
pub const ecdsa_p256 = @import("ecdsa_p256.zig");
pub const ed25519_batch = @import("ed25519_batch.zig");
pub const hash = @import("hash.zig");
pub const hash_kat = @import("hash_kat.zig");
pub const hkdf_tls13 = @import("hkdf_tls13.zig");
pub const hpke = @import("hpke.zig");
pub const jwt = @import("jwt.zig");
pub const kx_kat = @import("kx_kat.zig");
pub const kx = @import("kx.zig");
pub const mls_keyschedule = @import("mls_keyschedule.zig");
pub const node_short_id = @import("node_short_id.zig");
pub const ocsp = @import("ocsp.zig");
pub const pake = @import("pake.zig");
pub const random = @import("random.zig");
pub const ratchet = @import("ratchet.zig");
pub const rsa_verify = @import("rsa_verify.zig");
pub const sasl_scram_client = @import("sasl_scram_client.zig");
pub const sct = @import("sct.zig");
pub const secret = @import("secret.zig");
pub const secure_channel = @import("secure_channel.zig");
pub const sframe = @import("sframe.zig");
pub const shamir = @import("shamir.zig");
pub const sign_kat = @import("sign_kat.zig");
pub const sign = @import("sign.zig");
pub const tls_client = @import("tls_client.zig");
pub const tls_kat = @import("tls_kat.zig");
pub const tls_props = @import("tls_props.zig");
pub const tls_record = @import("tls_record.zig");
pub const tls_server = @import("tls_server.zig");
pub const tls = @import("tls.zig");
pub const totp = @import("totp.zig");
pub const treekem = @import("treekem.zig");
pub const tsumugi_handshake = @import("tsumugi_handshake.zig");
pub const tsumugi_session = @import("tsumugi_session.zig");
pub const vrf = @import("vrf.zig");
pub const webauthn = @import("webauthn.zig");
pub const x509_props = @import("x509_props.zig");
pub const x509_verify = @import("x509_verify.zig");
pub const x509 = @import("x509.zig");
pub const xwing = @import("xwing.zig");
// gen:mods:end

pub const Secret = secret.Secret;

test {
    // gen:tests:begin
    _ = aead;
    _ = aead_kat;
    _ = aead_stream;
    _ = age;
    _ = argon2_kdf;
    _ = cose;
    _ = crl;
    _ = ecdh_p256;
    _ = ecdsa_p256;
    _ = ed25519_batch;
    _ = hash;
    _ = hash_kat;
    _ = hkdf_tls13;
    _ = hpke;
    _ = jwt;
    _ = kx_kat;
    _ = kx;
    _ = mls_keyschedule;
    _ = node_short_id;
    _ = ocsp;
    _ = pake;
    _ = random;
    _ = ratchet;
    _ = rsa_verify;
    _ = sasl_scram_client;
    _ = sct;
    _ = secret;
    _ = secure_channel;
    _ = sframe;
    _ = shamir;
    _ = sign_kat;
    _ = sign;
    _ = tls_client;
    _ = tls_kat;
    _ = tls_props;
    _ = tls_record;
    _ = tls_server;
    _ = tls;
    _ = totp;
    _ = treekem;
    _ = tsumugi_handshake;
    _ = tsumugi_session;
    _ = vrf;
    _ = webauthn;
    _ = x509_props;
    _ = x509_verify;
    _ = x509;
    _ = xwing;
    // gen:tests:end
}
