//! Orochi library root — re-exports the package namespaces.
//! See docs/planning/00-architecture.md for the canonical design.
const std = @import("std");

/// Short git commit the binary was built from ("-dirty" when the tree had
/// uncommitted changes; "unknown" outside a checkout). Set in build.zig.
pub const git_commit = @import("build_info").git_commit;

/// The version simply IS the build's git revision — there is no separate
/// marketing version number, so every surface (boot banner, RPL_VERSION,
/// INFO) traces directly back to the exact commit that produced the binary.
pub const version = git_commit;
pub const version_full = git_commit;

// gen:mods:begin (auto-generated by tools/genroots.sh — do not edit between markers)
pub const crypto = @import("crypto/root.zig");
pub const daemon = @import("daemon/root.zig");
pub const proto = @import("proto/root.zig");
pub const substrate = @import("substrate/root.zig");
pub const wasm_transport_root = @import("wasm_transport_root.zig");
// gen:mods:end

/// OroWasm — pure-Zig sandboxed control-plane plugin host (subdir, not scanned
/// by genroots). See docs/planning/17-module-system.md §8.
pub const wasm_host = @import("wasm/host/root.zig");

/// Browser transport shim core (line framing + IRCv3 parse/escape for Ocean's
/// in-page WASM client). The `wasm32-freestanding` export wrapper lives in
/// `wasm/transport_shim.zig`; this is the std-only, natively-tested core (#32).
pub const browser_transport = @import("wasm/browser_transport.zig");

test {
    // 0.16 dropped refAllDeclsRecursive; reference each package so its tests run.
    std.testing.refAllDecls(@This());
    // gen:tests:begin
    _ = crypto;
    _ = daemon;
    _ = proto;
    _ = substrate;
    _ = wasm_transport_root;
    // gen:tests:end
    _ = wasm_host;
    _ = browser_transport;
}
